# Generated by Django 4.2.4 on 2023-09-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_body_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='test',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
